language: rust
rust:
    - nightly
sudo: false
cache: cargo

os:
    - osx
    - linux

script:
  - cargo test --all
  - rustdoc --test README.md --edition 2018 -L target/debug/deps -Z unstable-options
  - cargo bench --all
