cargo-features = ["namespaced-features", "rename-dependency"]

[package]
name = "tarpc"
version = "0.13.0"
authors = ["Adam Wright <adam.austin.wright@gmail.com>", "Tim Kuehn <timothy.j.kuehn@gmail.com>"]
edition = "2018"
namespaced-features = true
license = "MIT"
documentation = "https://docs.rs/tarpc"
homepage = "https://github.com/google/tarpc"
repository = "https://github.com/google/tarpc"
keywords = ["rpc", "network", "server", "api", "microservices"]
categories = ["asynchronous", "network-programming"]
readme = "../README.md"
description = "An RPC framework for Rust with a focus on ease of use."

[features]
serde = ["rpc/serde", "crate:serde", "serde/derive"]

[badges]
travis-ci = { repository = "google/tarpc" }

[dependencies]
log = "0.4"
serde = { optional = true, version = "1.0" }
tarpc-plugins = { path = "../plugins", version = "0.5.0" }
rpc = { package = "tarpc-lib", path = "../rpc", version = "0.1" }

[target.'cfg(not(test))'.dependencies]
futures-preview = "0.3.0-alpha.8"

[dev-dependencies]
humantime = "1.0"
futures-preview = { version = "0.3.0-alpha.8", features = ["compat", "tokio-compat"] }
bincode-transport = { version = "0.1", path = "../bincode-transport" }
env_logger = "0.5"
tokio = "0.1"
tokio-executor = "0.1"
